logo: # add logo name
title: Voyage 
comments: true
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl:  # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4
banner-title: Voyage
banner-desc: 

# Author settings
author-pic: amit.jpg 
author-name: Amit Singh
about-author: Software Engineer
email: amit2020cs@gmail.com
phone: 8630684627 
website: https://amit2020cs@github.io

# Social link
medium_url:    https://medium.com/@amit2020rocks
twitter_url:   https://twitter.com/amit2020cs
instagram_url: https://www.instagram.com/amit2020cs/
pinterest_url: https://in.pinterest.com/amit2020cs/
linkedin_url:  https://www.linkedin.com/in/amit2020cs/
facebook_url:  https://www.facebook.com/amit2020cs

# Disqus
discus_identifier: disqus_FU5CWK5kaj

# Tracker
analytics:

#Paginate
Paginate: 12
paginate_path: /page:num/



# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
